name: contact_cleaner
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - intel-openmp=2023.1.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.40.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - mkl=2022.1.0
  - numpy=1.24.2
  - openssl=3.1.0
  - pandas=2.0.0
  - pip=23.1
  - pthreads-win32=2.9.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - setuptools=67.6.1
  - six=1.16.0
  - tbb=2021.9.0
  - tk=8.6.12
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - xz=5.2.10
  - pip:
      - unidecode==1.3.6
